### ISSUE TITLE
Getting build error

### ISSUE THREAD

**Issue by lumyus** [rmccrystal/modernwarfare-cheat-rs#7]
```
Running cargo build --bin=mwc --package=mwc --message-format=json...
error: failed to resolve patches for https://github.com/rust-lang/crates.io-index

Caused by:
  failed to load source for dependency winit

Caused by:
  Unable to update C:\Users\cedri\Downloads\window-overlay\custom-winit

Caused by:
  failed to read C:\Users\cedri\Downloads\window-overlay\custom-winit\Cargo.toml

Caused by:
  Das System kann den angegebenen Pfad nicht finden. (os error 3)
```

Any idea what's going wrong?

**Comment by johnwalz97** [comment]
If you read the README or looked at the Cargo.toml, you'd see that some of the dependencies are private. For example: https://github.com/rmccrystal/modernwarfare-cheat-rs/blob/master/Cargo.toml#L11 shows that this project has a dependency on a library called memlib but that library is not public... The `../memlib-rs` is telling the rust compiler to look on the local machine for that library. Since only the author of this repo has that library (I would assume), it will only compile correctly on his machine.

**Comment by rmccrystal** [comment]
Bro just clone memlib-rs into the parent folder it's public however winutil is private so you will have to remake that
